### ISSUE TITLE
Feature: Allow users to upload their own glyphs

### ISSUE THREAD

**Issue by Xterionix** [NhanAZ/glyph#1]
Allowing users to upload their own glyph and then use the glyph's image as the icons for the buttons instead of the unicode character.

**Comment by NhanAZ** [comment]
Oh good idea. But do I have the skills to do it? I will look into it when I have some free time. If anyone can solve this problem, please feel free to open a PR!

**Comment by Xterionix** [comment]
I'll see if I can get it done

**Comment by NhanAZ** [comment]
Thanks for your idea. This issue has been resolved by https://github.com/NhanAZ/glyph/compare/e572ea391101...b0e40036a216
